//go:build windows

package webview2

// COM objects implemented in Go: the shared IUnknown half every Go-side
// callback object (event handlers, completion handlers, environment options)
// stands on. Split from com_windows.go, which keeps the outbound plumbing.

import (
	"sync"
	"sync/atomic"
	"unsafe"

	"golang.org/x/sys/windows"
)

// comServer is the IUnknown half of a COM object implemented in Go.
//
// Layout contract: it MUST be the first field of the concrete handler struct.
// A COM interface pointer is the address of a word holding the vtable address,
// so the concrete struct's address is only a valid interface pointer if the
// vtable word sits at offset zero.
type comServer struct {
	vtbl uintptr      // first word: address of the vtable. Do not move.
	refs int32        // COM reference count, touched from any thread
	iid  windows.GUID // the one interface, besides IUnknown, we answer QI for
	self any          // the concrete handler, recovered inside callbacks
}

// servers keeps every live Go-implemented COM object reachable.
//
// This map is the object's only GC root once it has been handed to WebView2:
// the runtime stores the pointer in its own memory, which the Go collector does
// not scan. Without an entry here the handler would be collected while the
// runtime still holds it, and the completion callback would land on freed
// memory. The entry is removed when the COM reference count reaches zero, so
// the lifetime is the COM lifetime, not the process lifetime.
var (
	serversMu sync.Mutex
	servers   = make(map[uintptr]*comServer)
)

// Callbacks generated by windows.NewCallback are allocated from a small,
// fixed-size table and are never freed, so they are created exactly once here
// at package initialisation rather than per handler instance. Creating them per
// object would exhaust the table after a few thousand navigations.
var (
	serverQueryInterfaceCallback = windows.NewCallback(serverQueryInterface)
	serverAddRefCallback         = windows.NewCallback(serverAddRef)
	serverReleaseCallback        = windows.NewCallback(serverRelease)

	// iunknownVtbl is the shared prefix of every handler vtable below.
	iunknownVtbl = IUnknownVtbl{
		QueryInterface: ComProc(serverQueryInterfaceCallback),
		AddRef:         ComProc(serverAddRefCallback),
		Release:        ComProc(serverReleaseCallback),
	}
)

// register publishes the object to COM with an initial reference count of one
// and returns the interface pointer to hand to the runtime.
//
// vtbl must address a package-level variable: Go globals never move, whereas a
// vtable on the heap would still be reachable but is needlessly hard to reason
// about when debugging a crash inside the runtime.
func (s *comServer) register(vtbl uintptr, iid windows.GUID, self any) uintptr {
	s.vtbl = vtbl
	s.iid = iid
	s.self = self
	atomic.StoreInt32(&s.refs, 1)

	this := uintptr(unsafe.Pointer(s))
	serversMu.Lock()
	servers[this] = s
	serversMu.Unlock()
	return this
}

func serverFor(this uintptr) *comServer {
	serversMu.Lock()
	defer serversMu.Unlock()
	return servers[this]
}

func serverQueryInterface(this, riid, ppv uintptr) uintptr {
	if ppv == 0 {
		return ePointer
	}
	server := serverFor(this)
	if server == nil {
		writeAddress(ppv, 0)
		return eNoInterface
	}
	iid, ok := readGUID(riid)
	if !ok {
		writeAddress(ppv, 0)
		return ePointer
	}
	// Only IUnknown and the object's own interface are supported. Answering
	// E_NOINTERFACE for anything else is not a limitation but the contract:
	// WebView2 probes for newer interfaces it might use, and a truthful "no"
	// makes it fall back instead of calling methods we never implemented.
	if iid == IIDIUnknown || iid == server.iid {
		writeAddress(ppv, this)
		atomic.AddInt32(&server.refs, 1)
		return sOK
	}
	writeAddress(ppv, 0)
	return eNoInterface
}

func serverAddRef(this uintptr) uintptr {
	server := serverFor(this)
	if server == nil {
		return 0
	}
	return uintptr(atomic.AddInt32(&server.refs, 1))
}

func serverRelease(this uintptr) uintptr {
	server := serverFor(this)
	if server == nil {
		return 0
	}
	remaining := atomic.AddInt32(&server.refs, -1)
	if remaining <= 0 {
		// Dropping the map entry drops the last GC root: the handler, and the
		// channel it closed over, become collectable. Nothing is freed by hand;
		// there is no C memory to free.
		serversMu.Lock()
		delete(servers, this)
		serversMu.Unlock()
		return 0
	}
	return uintptr(remaining)
}

// liveServerCount reports how many Go-implemented COM objects the runtime still
// holds. Only used by tests, to prove that handlers are released rather than
// leaked once creation completes.
func liveServerCount() int {
	serversMu.Lock()
	defer serversMu.Unlock()
	return len(servers)
}
